### ISSUE TITLE
好像不能设置 hiddenFromHomePage

### ISSUE THREAD

**Issue by eallion** [lmm214/immmmm#2]
好像不能设置 hiddenFromHomePage

**Comment by lmm214** [comment]
嗯，这个主题首页就是文章列表

**Comment by eallion** [comment]
> 嗯，这个主题首页就是文章列表

在原作者处提问，有人回答：

> You can use type = "archive" which achieve the same result.

[https://github.com/panr/hugo-theme-hello-friend/issues/153#issuecomment-626356358](https://github.com/panr/hugo-theme-hello-friend/issues/153#issuecomment-626356358)
